TEXT = {
    "zh": {
        "site_title": "台灣空氣品質儀表板",
        "site_subtitle": "Taiwan Air Quality Dashboard",
        "language": "語言 / Language",
        "language_toggle_label": "語言切換",
        "menu_title": "導覽",
        "home_menu": "首頁",
        "home_title": "台灣空氣品質儀表板",
        "home_desc": "請選擇想查看的分析頁面",
        "go_to_page": "前往頁面",
        "overview": "總覽",
        "trend": "台灣 AQI 趨勢",
        "county": "各縣市空氣品質分析",
        "hours": "高污染時段",
        "overview_desc": "查看整體 AQI 指標與快速摘要",
        "trend_desc": "查看每日平均 AQI 變化趨勢",
        "county_desc": "查看各縣市平均 AQI 分布",
        "hours_desc": "查看一天中高污染時段分布",
        "avg_aqi": "平均 AQI",
        "max_aqi": "最高 AQI",
        "high_pollution_count": "高污染時段數",
        "line_chart_title": "台灣 AQI 趨勢",
        "date_label": "日期",
        "month_label": "月份",
        "aqi_value_label": "AQI 數值",
        "rolling_7d_avg": "7 日滾動平均 AQI",
        "legend_title": "線條",
        "daily_legend": "Daily AQI",
        "rolling_legend": "7-day Rolling Avg",
        "chart_zoom_hint": "可用滑鼠滾輪縮放、拖曳平移；雙擊圖表可回到原始視角。",
        "hours_x_axis_label": "時段 (小時)",
        "hours_y_axis_ratio_label": "高污染機率",
        "hours_y_axis_count_label": "高污染次數",
        "hours_tooltip_county": "縣市",
        "hours_tooltip_hour": "時段",
        "hours_tooltip_ratio": "機率",
        "hours_tooltip_count": "高污染次數",
        "county_chart_title": "各縣市汙染狀況分析",
        "hours_chart_title": "高污染時段",
        "back_home_button": "回到首頁",
        "aqi_guide_title": "AQI 分級說明",
        "aqi_good_label": "良好 / Green",
        "aqi_good_text": "可正常進行戶外活動",
        "county_stability_title": "各縣市空氣品質分析",
        "county_mean_aqi": "平均 AQI",  
        "county_std_aqi": "AQI 波動度（標準差）",
        "county_high_pol_ratio": "高污染比例",
        "county_total_count": "觀測總數",
        "county_mean_rank": "平均 AQI 排名",
        "county_std_rank": "波動度排名",
        "county_ratio_rank": "高污染比例排名",
        "county_page_intro": "這頁從三個角度比較各縣市空氣品質：平均 AQI 代表整體污染程度，AQI 波動度代表日常變化是否劇烈，高污染比例代表 AQI 超過 100 的發生頻率。",
        "hours_risk_analysis_title": "高污染風險分析",
        "hours_risk_analysis_desc": "本頁面顯示高污染 (AQI > 100) 最可能發生的時段。\n基於**機率/風險**的分析結果與原始的**次數統計分析**進行比較。",
        "hours_overview_title": "總覽",
        "hours_highest_risk_hour": "最高風險時段",
        "hours_highest_risk_ratio": "最高風險比例",
        "hours_avg_hourly_risk": "平均每小時風險",
        "hours_overall_risk_title": "各時段整體高污染風險",
        "hours_overall_risk_caption": "此圖表顯示台灣每個時段觀測到 AQI > 100 的機率。",
        "hours_overall_na": "目前無整體機率資料表。",
        "hours_county_risk_title": "縣市風險比較",
        "hours_county_risk_caption": "選擇一個縣市，查看該縣市高污染機率在各時段的變化。",
        "hours_county_no_data": "無所選縣市的風險資料。",
        "hours_county_na": "目前無縣市層級的機率資料。",
        "hours_orig_count_title": "原始次數分析",
        "hours_orig_count_caption": "此區塊保留原始的次數統計視圖供比較。次數顯示事件發生的總數；風險比例則顯示事件發生的可能性。",
        "hours_interpretation_title": "數據解讀",
        "hours_interpretation_desc": 
        "- **各時段整體高污染風險**用來識別一天中高污染最集中的時間帶。若某些時段的比例明顯較高，代表高污染事件並非隨機出現，而是具有固定的日內分布結構。\n"
        "- **縣市風險比較**透過縣市篩選，可以觀察個別地區的高污染時段是否與整體趨勢一致。若某縣市的尖峰時段與整體分布不同，通常反映地方性排放來源、交通模式或地形條件造成的差異。\n"
        "- **比例與次數交叉判讀**高污染比例代表發生頻率，而原始次數代表實際事件量。比例高但次數低可能只是偶發事件；比例與次數同時偏高，則代表穩定且高風險的污染時段。\n"
        "- **風險判斷**若某些時段在整體與多數縣市中都呈現較高比例，代表該時段屬於結構性高風險區間，適合作為監測與改善的優先重點。",
        "county_top_std_title": "波動度最高",
        "county_top_std_desc": "代表 AQI 日常變化較劇烈",
        "county_top_ratio_title": "高污染比例最高",
        "county_top_ratio_desc": "代表 AQI 超過 100 的情況較常出現",
        "county_chart_mean_title": "平均 AQI",
        "county_chart_mean_desc": "數值越高，代表長期平均空氣品質越差。",
        "county_chart_std_title": "AQI 波動度（標準差）",
        "county_chart_std_desc": "數值越高，代表日與日之間變化越明顯。",
        "county_chart_ratio_title": "高污染比例",
        "county_chart_ratio_desc": "比例越高，代表 AQI 超過 100 的情況越常發生。",
        "county_table_title": "縣市指標明細",
        "county_table_desc": "下表用來查看完整數值與排序，可搭配上方圖表交叉比較。",
        "county_how_to_read_body": "若某縣市平均 AQI 高，代表整體污染水準偏高；若波動度也高，表示不只平均較差，日常空氣品質也較不穩定；若高污染比例同時偏高，則代表 AQI 超過 100 的情況更常出現。三個指標一起看，比單看平均值更能判斷空氣品質風險。",
        "county_name_reference_title": "縣市中英文對照與縮寫",
        "county_zh": "中文縣市名",
        "county_en": "English County Name",
        "county_abbrev": "英文縮寫",
        "county_overall_insight_title": "綜合解讀",
        "county_overall_insight_body": "右上角且圓較大的縣市，表示不僅平均污染程度較高，變動也較劇烈，且高污染事件發生頻率高，屬於整體風險最高的區域。 相對地，左下角且圓較小的縣市，代表空氣品質穩定且較少出現高污染情況。",
        "county_high_risk_label": "較需注意的縣市",
        "county_good_label": "表現較穩定的縣市",
        "no_data": "無明顯分類結果",
        "aqi_moderate_label": "普通 / Yellow",
        "aqi_moderate_text": "空氣品質可接受，但敏感族群（如呼吸道疾病患者）應減少體力消耗",
        "aqi_polluted_label": "污染 / Red",
        "aqi_polluted_text": "已屬空氣污染，請減少戶外活動",
        "trend_interpretation_title": "趨勢解讀",
        "trend_interpretation_body": """Daily AQI 用來顯示短期波動，而 7-day rolling average 則用來呈現較整體的趨勢。<br>
                                    如果 Daily AQI 明顯升高，但 7-day rolling average 沒有明顯上升，通常代表這比較像短期污染事件。<br>
                                    如果兩條線一起上升，則表示空氣品質變差可能不是單日現象，而是較持續的惡化趨勢。<br>
                                    相反地，如果 7-day rolling average 逐漸下降，則代表整體空氣品質可能正在慢慢改善。""",
        "current_status_title": "目前狀態判讀",
        "current_status_placeholder": "目前資料不足，暫時無法判讀整體趨勢。",
        "status_insufficient_data": "目前資料不足，暫時無法判讀整體趨勢。",
        "status_short_term_spike": "最新 Daily AQI 明顯高於 7-day rolling average，代表最近可能出現短期污染升高或單次污染事件。",
        "status_sustained_pollution": "最新 Daily AQI 與 7-day rolling average 都維持在偏高水準，代表目前可能處於持續性的高污染狀態。",
        "status_improving_trend": "7-day rolling average 比前一天下降，代表整體空氣品質可能正在逐步改善。",
        "status_normal_variation": "最新 Daily AQI 與 7-day rolling average 差距不大，且移動平均變化平穩，代表目前整體以正常波動為主。",
        "status_worsening_trend": "7-day rolling average 持續上升，代表近期空氣品質可能有逐步變差的趨勢。",
        "monthly_pattern_title": "月度 AQI 型態（可選）",
        "monthly_avg_aqi": "月平均 AQI",
        "daily_avg_aqi": "每日平均 AQI",
        "county_avg_aqi": "各縣市平均 AQI",
        "high_pollution_hours_label": "高污染次數",
        "home_button_overview": "進入總覽頁",
        "home_button_trend": "進入趨勢頁",
        "home_button_county": "進入縣市分析頁",
        "home_button_hours": "進入高污染時段頁",
        "home_button_spike": "進入異常偵測頁",
        "spike_title": "異常污染飆高偵測",
        "spike_desc": "統計模型找出與近期基準對比出現極端污染事件",
        "spike_pollutant_select": "選擇污染物",
        "spike_method_select": "偵測方法",
        "spike_method_rolling_threshold": "滾動平均閾值",
        "spike_method_zscore": "Z 分數異常值",
        "spike_county_select": "縣市篩選",
        "spike_param_settings": "進階參數設定",
        "spike_rolling_window": "滾動時間窗 (小時)",
        "spike_ratio_threshold": "異常高標倍數",
        "spike_zscore_threshold": "Z-Score 閾值",
        "spike_min_value": "最低濃度限制",
        "spike_calculating": "正在計算異常資料...",
        "spike_no_data": "無發現異常飆高事件。請嘗試調整參數或選擇不同縣市。",
        "spike_total_count": "總計飆高次數",
        "spike_max_title": "最高觀測數值",
        "spike_top_site": "飆高最頻繁測站",
        "spike_chart_title": "污染飆高時間序列檢視",
        "spike_site": "測站",
        "spike_strength": "飆高強度",
        "spike_interpretation_text": "> **數據解讀**\n> \n> - **紅點 (Spikes)** 代表污染濃度顯著高於近期的正常水準。\n> - **滾動平均法**：捕捉短期內快速惡化的突發事件（例如：附近的局部污染源排放）。\n> - **Z-Score 法**：捕捉偏離該測站長期平均背景濃度的端點極值。\n> - 頻繁產生 Spike 的測站，通常暗示周遭受間歇性污染源影響，而非長期的穩定污染。",
                "county_overview_title": "各縣市污染特性與穩定度",
        "county_overview_desc": "各縣市污染程度與日常波動性之總覽",
        "county_risk_title": "縣市風險進階分析",
        "county_risk_desc": "高風險縣市發掘與綜合風險分數排行",
        "risk_score": "風險分數",
        "risk_rank": "風險排名",
        "county_risk_intro": "本頁面基於長期平均污染水準、日常波動度以及極端空污頻率，綜合評估各縣市的空氣品質空污風險。分數越高，代表暴露在此環境的綜合風險越高且越不穩定。",
        "risk_score_chart_title": "綜合空污風險分數 (0-100)",
        "risk_score_methodology": "計算方法：為消除共線性(雙重計算)，以相對波動度 (CV=標準差/平均值) 與正規化平均 AQI 的等權重計算為基礎，並將高污染比率作為極端懲罰乘數轉換而成。",
        "top_risky_counties_title": "前五大高風險縣市",
        "view_individual_metrics": "查看單一指標排序分布",
        "home_button_county_risk": "進入縣市風險頁",
        "na": "無",
    },
    "en": {
        "site_title": "Taiwan Air Quality Dashboard",
        "site_subtitle": "Taiwan Air Quality Dashboard",
        "language": "Language / 語言",
        "language_toggle_label": "Language",
        "menu_title": "Navigation",
        "home_menu": "Home",
        "home_title": "Taiwan Air Quality Dashboard",
        "home_desc": "Choose a page to explore the analysis",
        "go_to_page": "Go to page",
        "overview": "Overview",
        "trend": "Taiwan AQI Trend",
        "county": "County Air Quality Analysis",
        "hours": "High Pollution Hours",
        "overview_desc": "View overall AQI metrics and quick summary",
        "trend_desc": "View daily average AQI trend",
        "county_desc": "View average AQI across counties",
        "hours_desc": "View high pollution hours throughout the day",
        "avg_aqi": "Average AQI",
        "max_aqi": "Max AQI",
        "high_pollution_count": "High Pollution Count",
        "line_chart_title": "Taiwan AQI Trend",
        "date_label": "Date",
        "month_label": "Month",
        "aqi_value_label": "AQI",
        "rolling_7d_avg": "7-day Rolling Avg AQI",
        "legend_title": "Series",
        "daily_legend": "Daily AQI",
        "rolling_legend": "7-day Rolling Avg",
        "chart_zoom_hint": "Use mouse wheel to zoom and drag to pan; double-click the chart to reset the original view.",
        "hours_x_axis_label": "Hour of Day",
        "hours_y_axis_ratio_label": "High Pollution Probability",
        "hours_y_axis_count_label": "High Pollution Count",
        "hours_tooltip_county": "County",
        "hours_tooltip_hour": "Hour",
        "hours_tooltip_ratio": "Probability Ratio",
        "hours_tooltip_count": "High Pollution Count",
        "county_chart_title": "Pollution by County",
        "hours_chart_title": "High Pollution Hours",
        "back_home_button": "Back to Home",
        "aqi_guide_title": "AQI Interpretation",
        "aqi_good_label": "Good / Green",
        "aqi_good_text": "Normal outdoor activity",
        "county_stability_title": "County Air Quality Analysis",
        "county_mean_aqi": "Mean AQI",
        "county_std_aqi": "AQI Volatility (Std Dev)",
        "county_high_pol_ratio": "High Pollution Ratio",
        "county_total_count": "Total Observations",
        "county_mean_rank": "Mean Rank",
        "county_std_rank": "Volatility Rank",
        "county_ratio_rank": "Ratio Rank",
        "county_interpretation_text": "High average AQI indicates consistently polluted areas, whereas high volatility (Std Dev) highlights counties prone to sudden, extreme pollution events. The High Pollution Ratio shows how often a county exceeds AQI 100.",
        "county_page_intro": "This page compares county-level air quality from three perspectives: mean AQI reflects the overall pollution level, AQI volatility reflects how unstable day-to-day conditions are, and the high-pollution ratio shows how often AQI exceeds 100.",
        "hours_risk_analysis_title": "High Pollution Risk Analysis",
        "hours_risk_analysis_desc": "This page shows when high pollution (AQI > 100) is most likely to occur.\nIt compares **probability/risk-based results** with the original **count-based analysis**.",
        "hours_overview_title": "Overview",
        "hours_highest_risk_hour": "Highest-risk hour",
        "hours_highest_risk_ratio": "Highest risk ratio",
        "hours_avg_hourly_risk": "Average hourly risk",
        "hours_overall_risk_title": "Overall High Pollution Risk by Hour",
        "hours_overall_risk_caption": "This chart shows the probability of observing AQI > 100 at each hour of Taiwan.",
        "hours_overall_na": "Overall probability table is not available.",
        "hours_county_risk_title": "County-level Risk Comparison",
        "hours_county_risk_caption": "Select a county to see how the probability of high pollution changes across hours.",
        "hours_county_no_data": "No county-level risk data available for the selected county.",
        "hours_county_na": "County-level probability table is not available.",
        "hours_orig_count_title": "Original Count-based Analysis",
        "hours_orig_count_caption": "This section keeps the original count-based view for comparison. Count shows how many events occurred; risk ratio shows how likely they are.",
        "hours_interpretation_title": "Interpretation",
        "hours_interpretation_desc":  
        "- **Overall High Pollution Risk by Hour**identifies the time windows where high pollution events are most concentrated. Higher ratios in specific hours indicate structured daily patterns rather than random occurrences.\n"
        "- **County-level Risk Comparison**allow comparison between individual counties and the overall trend. If a county's peak hours differ from the overall pattern, it often reflects local emission sources, traffic behavior, or geographic conditions.\n"
        "- **Ratio vs Count Interpretation** compares frequency and actual event volume. A high ratio with low counts may indicate occasional spikes, while both high ratio and high counts suggest consistently high-risk periods.\n"
        "- **Risk Identification** highlights time periods that consistently show elevated ratios across both overall and county-level views, indicating structural high-risk intervals that should be prioritized for monitoring and intervention.",
        "county_top_mean_desc": "Indicates a higher long-term overall pollution level",
        "county_top_std_title": "Highest Volatility",
        "county_top_std_desc": "Indicates stronger day-to-day AQI fluctuations",
        "county_top_ratio_title": "Highest High-Pollution Ratio",
        "county_top_ratio_desc": "Indicates AQI exceeds 100 more frequently",
        "county_chart_mean_title": "Mean AQI",
        "county_chart_mean_desc": "Higher values indicate worse long-term average air quality.",
        "county_chart_std_title": "AQI Volatility (Std Dev)",
        "county_chart_std_desc": "Higher values indicate stronger day-to-day variation.",
        "county_chart_ratio_title": "High-Pollution Ratio",
        "county_chart_ratio_desc": "Higher values indicate AQI exceeds 100 more often.",
        "county_table_title": "County Metrics Table",
        "county_table_desc": "Use the table below to inspect detailed values and rankings alongside the charts above.",
        "county_how_to_read_body": "If a county has a high mean AQI, its overall pollution level is relatively high. If its volatility is also high, daily air quality is not only worse on average but also less stable. If the high-pollution ratio is high as well, AQI above 100 occurs more frequently. Looking at these three metrics together provides a better picture of air-quality risk than using the mean alone.",
        "county_name_reference_title": "County Name Reference and Abbreviation",
        "county_zh": "Chinese County Name",
        "county_en": "English County Name",
        "county_abbrev": "Abbreviation",
        "county_overall_insight_title": "Interpretation",
        "county_overall_insight_body": "Regions located in the upper-right with larger circles indicate not only higher average pollution but also greater variability and more frequent high pollution events, representing the highest overall risk. In contrast, regions in the lower-left with smaller circles indicate stable and generally clean air conditions.",
        "county_high_risk_label": "Regions currently requiring more attention",
        "county_good_label": "Regions currently showing more stable performance",
        "no_data": "No clear group identified",
        "aqi_moderate_label": "Moderate / Yellow",
        "aqi_moderate_text": "Air quality is acceptable, but sensitive groups should reduce physical exertion",
        "aqi_polluted_label": "Polluted / Red",
        "aqi_polluted_text": "Considered air pollution; reduce outdoor activity",
        "trend_interpretation_title": "How To Read This Trend",
        "trend_interpretation_body": """Daily AQI helps show short-term fluctuations, while the 7-day rolling average highlights the broader trend.<br> 
                                    If daily AQI spikes but the rolling average does not rise much, it usually suggests a short-term pollution event.<br> 
                                    If both lines rise together, it indicates a more sustained deterioration in air quality.<br> 
                                    On the other hand, if the rolling average gradually declines, it suggests that overall air quality is improving over time.""",
        "current_status_title": "Current Status",
        "current_status_placeholder": "Not enough data to interpret the current trend yet.",
        "status_insufficient_data": "Not enough data to interpret the current trend yet.",
        "status_short_term_spike": "The latest daily AQI is clearly higher than the 7-day rolling average, it may indicate a short-term pollution spike or a one-time pollution event.",
        "status_sustained_pollution": "Both OF the latest daily AQI and the 7-day rolling average remain at relatively high levels, it suggests a sustained high-pollution period.",
        "status_improving_trend": "The 7-day rolling average is lower than the previous day, overall air quality may be gradually improving.",
        "status_normal_variation": "The latest daily AQI stays close to the 7-day rolling average and the rolling trend remains stable, the current pattern is more consistent with normal short-term variation.",
        "status_worsening_trend": "The 7-day rolling average continues to rise, it suggests that air quality may be gradually deteriorating.",
        "monthly_pattern_title": "Monthly AQI Pattern (Optional)",
        "monthly_avg_aqi": "Monthly Average AQI",
        "daily_avg_aqi": "Daily Average AQI",
        "county_avg_aqi": "Average AQI by County",
        "high_pollution_hours_label": "High Pollution Count",
        "home_button_overview": "Open Overview",
        "home_button_trend": "Open Trend Page",
        "home_button_county": "Open County Page",
        "home_button_hours": "Open High Pollution Page",
        "home_button_spike": "Open Spike Detection",
        "spike_title": "Pollution Spike Detection",
        "spike_desc": "Detect sudden pollution surges against recent baselines.",
        "spike_pollutant_select": "Select Pollutant",
        "spike_method_select": "Detection Method",
        "spike_method_rolling_threshold": "Rolling Mean Threshold",
        "spike_method_zscore": "Z-Score Anomaly",
        "spike_county_select": "Filter by County",
        "spike_param_settings": "Advanced Parameter Settings",
        "spike_rolling_window": "Rolling Window (Hours)",
        "spike_ratio_threshold": "Ratio Above Baseline",
        "spike_zscore_threshold": "Z-Score Threshold",
        "spike_min_value": "Minimum Value",
        "spike_calculating": "Calculating spike anomalies...",
        "spike_no_data": "No pollution spikes detected. Try adjusting parameters or selecting another county.",
        "spike_total_count": "Total Spike Events",
        "spike_max_title": "Max Observed Value",
        "spike_top_site": "Site w/ Most Spikes",
        "spike_chart_title": "Time-Series Spike View",
        "spike_site": "Site",
        "spike_strength": "Spike Strength",
        "spike_interpretation_text": "> **Interpretation**\n> \n> - **Red markers (Spikes)** represent pollution values significantly higher than recent normal levels.\n> - **Rolling Threshold** captures sudden deterioration (e.g., local intermittent emissions).\n> - **Z-Score** captures outliers against a site's long-term historical average capability.\n> - Stations displaying frequent spikes typically indicate exposure to short-term event-driven pollution rather than consistently poor overall air quality.",
                "county_overview_title": "County Pollution Profiles & Stability",
        "county_overview_desc": "Overview of pollution levels and volatility",
        "county_risk_title": "County Risk Analysis",
        "county_risk_desc": "Identify high-risk areas via an aggregated score",
        "risk_score": "Risk Score",
        "risk_rank": "Risk Rank",
        "county_risk_intro": "This page evaluates overall air quality risk by integrating long-term pollution, volatility, and frequency of extreme events. A higher score indicates a more hazardous environment.",
        "risk_score_chart_title": "Overall County Risk Score (0-100)",
        "risk_score_methodology": "Methodology: To eliminate double-counting, we use the Coefficient of Variation (Std/Mean) and Normalized Mean AQI for a decoupled base score, multiplied by an extreme event penalty factor (1 + High Pollution Ratio).",
        "top_risky_counties_title": "Top 5 High-Risk Counties",
        "view_individual_metrics": "View Individual Component Metrics",
        "home_button_county_risk": "Go to County Risk Page",
        "na": "N/A",
    }
}