TEXT = {
    "zh": {
        # pages/trend.py
        "aqi_value_label": "AQI 數值",
        "legend_title": "線條",
        "daily_legend": "Daily AQI",
        "rolling_legend": "7-day Rolling Avg",
        "trend": "台灣 AQI 趨勢",
        "aqi_good_label": "良好 / Green",
        "aqi_moderate_label": "普通 / Yellow",
        "aqi_polluted_label": "污染 / Red",
        "aqi_guide_title": "AQI 分級說明",
        "aqi_good_text": "可正常進行戶外活動",
        "aqi_moderate_text": "空氣品質可接受，但敏感族群（如呼吸道疾病患者）應減少體力消耗",
        "aqi_polluted_text": "已屬空氣污染，請減少戶外活動",
        "no_trend_data": "目前無趨勢資料可顯示。",
        "trend_interpretation_title": "趨勢解讀",
        "trend_interpretation_body": """Daily AQI 用來顯示短期波動，而 7-day rolling average 則用來呈現較整體的趨勢。<br>
                        如果 Daily AQI 明顯升高，但 7-day rolling average 沒有明顯上升，通常代表這比較像短期污染事件。<br>
                        如果兩條線一起上升，則表示空氣品質變差可能不是單日現象，而是較持續的惡化趨勢。<br>
                        相反地，如果 7-day rolling average 逐漸下降，則代表整體空氣品質可能正在慢慢改善。""",
        "current_status_title": "目前狀態判讀",
        "current_status_placeholder": "目前資料不足，暫時無法判讀整體趨勢。",
        "status_insufficient_data": "目前資料不足，暫時無法判讀整體趨勢。",
        "status_short_term_spike": "最新 Daily AQI 明顯高於 7-day rolling average，代表最近可能出現短期污染升高或單次污染事件。",
        "status_sustained_pollution": "最新 Daily AQI 與 7-day rolling average 都維持在偏高水準，代表目前可能處於持續性的高污染狀態。",
        "status_improving_trend": "7-day rolling average 比前一天下降，代表整體空氣品質可能正在逐步改善。",
        "status_normal_variation": "最新 Daily AQI 與 7-day rolling average 差距不大，且移動平均變化平穩，代表目前整體以正常波動為主。",
        "status_worsening_trend": "7-day rolling average 持續上升，代表近期空氣品質可能有逐步變差的趨勢。",
        # pages/high_pollution_hours.py
        "hours_y_axis_ratio_label": "高污染機率",
        "hours_y_axis_count_label": "高污染次數",
        "hours_tooltip_county": "縣市",
        "hours_tooltip_ratio": "機率",
        "hours_tooltip_count": "高污染次數",
        "hours_risk_analysis_desc": "本頁面顯示高污染 (AQI > 100) 最可能發生的時段。\n基於**機率/風險**的分析結果與原始的**次數統計分析**進行比較。",
        "hours_overview_title": "總覽",
        "hours_highest_risk_hour": "最高風險時段",
        "hours_highest_risk_ratio": "最高風險比例",
        "hours_avg_hourly_risk": "平均每小時風險",
        "hours_overall_risk_title": "各時段整體高污染風險",
        "hours_overall_risk_caption": "此圖表顯示台灣每個時段觀測到 AQI > 100 的機率。",
        "hours_overall_na": "目前無整體機率資料表。",
        "hours_county_risk_title": "縣市風險比較",
        "hours_county_risk_caption": "選擇一個縣市，查看該縣市高污染機率在各時段的變化。",
        "hours_county_no_data": "無所選縣市的風險資料。",
        "hours_county_na": "目前無縣市層級的機率資料。",
        "hours_orig_count_title": "原始次數分析",
        "hours_orig_count_caption": "此區塊保留原始的次數統計視圖供比較。次數顯示事件發生的總數；風險比例則顯示事件發生的可能性。",
        "hours_interpretation_title": "數據解讀",
        "hours_interpretation_desc": 
        "- **各時段整體高污染風險**用來識別一天中高污染最集中的時間帶。若某些時段的比例明顯較高，代表高污染事件並非隨機出現，而是具有固定的日內分布結構。\n"
        "- **縣市風險比較**透過縣市篩選，可以觀察個別地區的高污染時段是否與整體趨勢一致。若某縣市的尖峰時段與整體分布不同，通常反映地方性排放來源、交通模式或地形條件造成的差異。\n"
        "- **比例與次數交叉判讀**高污染比例代表發生頻率，而原始次數代表實際事件量。比例高但次數低可能只是偶發事件；比例與次數同時偏高，則代表穩定且高風險的污染時段。\n"
        "- **風險判斷**若某些時段在整體與多數縣市中都呈現較高比例，代表該時段屬於結構性高風險區間，適合作為監測與改善的優先重點。",
        # utils.py
        "back_home_button": "首頁",
        # shared
        "date_label": "日期",
        "county": "各縣市空氣品質分析",
        "all_option": "全部",
        "na": "無",
        "loading_raw_data": "正在載入原始數據...",
        "data_not_found": "找不到資料。",
        "hours_x_axis_label": "時段 (小時)",
        "hours_tooltip_hour": "時段",
        "county_mean_aqi": "平均 AQI",  
        "county_std_aqi": "AQI 波動度（標準差）",
        "county_high_pol_ratio": "高污染比例",
        # pages/county_analysis.py
        "county_total_count": "觀測總數",
        "county_page_intro": "本頁面以平均 AQI、波動度與高污染比例，綜合比較各縣市的空氣品質特性與穩定度。",
        "county_how_to_read_body": "可先看氣泡圖掌握整體分布，再切換到單一指標與完整資料表深入比較。",
        "county_overall_insight_title": "綜合解讀",
        "county_overall_insight_body": "右上角且圓較大的縣市，表示不僅平均污染程度較高，變動也較劇烈，且高污染事件發生頻率高，屬於整體風險最高的區域。 相對地，左下角且圓較小的縣市，代表空氣品質穩定且較少出現高污染情況。",
        "county_high_risk_label": "較需注意的縣市",
        "county_good_label": "表現較穩定的縣市",
        "county_zh": "縣市（中文）",
        "county_en": "縣市（英文）",
        "county_abbrev": "縮寫",
        "no_data": "無明顯分類結果",
        # app.py (home)
        "home_title": "台灣空氣品質儀表板",
        "home_menu": "首頁",
        "home_desc": "請選擇想查看的分析頁面",
        "hours": "高污染時段",
        "county_overview_title": "各縣市污染特性與穩定度",
        "county_risk_title": "各縣市風險進階分析",
        "spike_title": "異常污染飆高偵測",
        "forecast_menu": "AQI 預測系統",
        "trend_desc": "查看每日平均 AQI 變化趨勢",
        "county_overview_desc": "查看各縣市污染程度與日常波動性",
        "county_risk_desc": "查看高風險縣市與綜合風險分數排行",
        "hours_desc": "查看一天中高污染時段分布",
        "spike_desc": "查看不合理的異常污染突增事件",
        "forecast_desc": "查看未來 24 小時 AQI 預測趨勢",
        "home_button_trend": "進入趨勢頁",
        "home_button_county": "進入縣市分析頁",
        "home_button_hours": "進入高污染時段頁",
        "home_button_spike": "進入異常偵測頁",
        "home_button_forecast": "進入 AQI 預測頁",
        # pages/spike_detection.py
        "spike_pollutant_select": "選擇污染物",
        "spike_method_select": "偵測方法",
        "spike_method_rolling_threshold": "滾動平均閾值",
        "spike_method_zscore": "Z 分數異常值",
        "spike_county_select": "縣市篩選",
        "spike_param_settings": "進階參數設定",
        "spike_rolling_window": "滾動時間窗 (小時)",
        "spike_ratio_threshold": "異常高標倍數",
        "spike_zscore_threshold": "Z-Score 閾值",
        "spike_min_value": "最低濃度限制",
        "spike_calculating": "正在計算異常資料...",
        "spike_no_data": "無發現異常飆高事件。請嘗試調整參數或選擇不同縣市。",
        "hours_spike_title": "異常熱力圖",
        "hours_spike_caption": "用「小時 × 星期」先看異常通常集中在哪些時間帶，先抓可疑時段。",
        "hours_y_axis_weekday_label": "星期",
        "hours_spike_count_legend": "異常突增次數",
        "hours_tooltip_weekday": "星期",
        "hours_tooltip_spike_count": "短時異常突增次數",
        "wd_1": "星期一", "wd_2": "星期二", "wd_3": "星期三", "wd_4": "星期四", "wd_5": "星期五", "wd_6": "星期六", "wd_7": "星期日",
        "spike_total_count": "總計飆高次數",
        "spike_max_title": "最高觀測數值",
        "spike_top_site": "飆高最頻繁測站",
        "spike_chart_title": "時間序列事件圖",
        "spike_site": "測站",
        "spike_strength": "飆高強度",
        "spike_event_tab": "異常事件偵測",
        "spike_summary_tab": "異常偵測摘要",
        "spike_interpretation_text": "**數據解讀**\n\n- **熱力圖先看分布**：若特定星期與時段反覆出現高值，表示異常事件可能不是隨機噪音，而是具有固定發生模式。\n- **時間序列再看細節**：灰線代表背景變化，紅點代表偏離背景的異常突增。紅點連續出現時，通常代表同一波污染事件延續。\n- **實務判讀順序**：先在熱力圖找高風險時段，再回到時間序列確認日期、強度與持續時間，避免只看單一尖峰就過度解讀。",
        "spike_detection_summary": "異常偵測摘要",
        "spike_sample_table_title": "查看異常樣本資料",
        "spike_sample_note": "下表為異常事件前 20 筆樣本。",
        "county_risk_spike_interpretation_text": "**數據解讀**\n\n- **縣市分布圖**：用來比較各縣市異常事件總量。長期高於其他縣市者，通常代表該區有持續性風險來源。\n- **時段分布圖**：用來辨識一天中最常發生異常的時段。若集中在固定時段，通常與規律活動或固定排放行為相關。\n- **交叉判讀重點**：同時在特定縣市與特定時段都偏高時，優先列為監測與稽查對象；僅短暫升高時，建議同步比對天氣與站點狀態後再下結論。",
        # pages/county_risk.py
        "risk_score": "風險分數",
        "risk_rank": "風險排名",
        "county_risk_intro": "本頁面基於長期平均污染水準、日常波動度以及極端空污頻率，綜合評估各縣市的空氣品質空污風險。分數越高，代表暴露在此環境的綜合風險越高且越不穩定。",
        "risk_score_chart_title": "綜合空污風險分數 (0-100)",
        "risk_details_title": "查看風險計算細節",
        "risk_details_intro": "- 先以縣市聚合計算平均 AQI、波動度與高污染比例。\n- 將平均 AQI 與 CV 正規化後各占 50%。\n- 再乘上高污染比例懲罰項，最後換算為 0-100 分。",
        "risk_time_range_caption": "計算資料時間範圍：{start} ~ {end}",
        "risk_formula_table_title": "完整計算欄位表",
        "risk_component_mean_norm": "平均 AQI 正規化",
        "risk_component_cv_norm": "CV 正規化",
        "risk_component_base_score": "基礎分數",
        "risk_component_raw_risk": "懲罰後原始風險",
        "risk_formula_note": "公式：risk_score = normalize((0.5 * mean_aqi_norm + 0.5 * cv_aqi_norm) * (1 + high_pollution_ratio)) * 100",
        "home_button_county_risk": "進入縣市風險頁",
        "analyzing_data": "正在分析全台空氣品質資料...",
        "risk_ranking_tab": "風險排名",
        "spike_detection_tab": "異常偵測",
        "highest_risk": "最高風險",
        "total_anomalies": "異常總數",
        "risk_score_table_title": "風險分數表",
        "spike_details_title": "查看異常判讀細節",
        # pages/county_analysis.py
        "highest_risk_county": "最高風險縣市",
        "best_county": "最佳縣市",
        "highest_volatility": "波動度最高",
        "county_overview_chart": "各縣市大圖總覽",
        "indicator_ranking": "各指標排序",
        "mean_aqi_ranking": "平均 AQI 排序",
        "volatility_ranking": "波動度（Std）排序",
        "high_pollution_ratio_ranking": "高污染比例排序",
        "complete_data_table": "完整數據表",
        "county_name_comparison": "縣市中英文對照",
        "classification_criteria": "分類標準",
        "raw_data_preview": "原始數據預覽（前 20 筆）",
        "loading_analysis": "正在載入全台空氣品質數據並分析穩定度...",
        "stable_air_quality": "目前全台空氣品質穩定",
        "county_risk_table_not_found": "找不到縣市風險表，請先執行 main.py 資料流程。",
        "county_tab_overview": "概覽圖",
        "county_tab_metrics": "單一指標",
        "county_tab_data": "完整數據",
        "details_info": "詳細資訊",
        "county_high_risk_criteria_label": "高風險縣市",
        "county_high_risk_criteria_line1": "平均 AQI > {risk_threshold}，且",
        "county_high_risk_criteria_line2": "同時滿足：平均 AQI > {mean_avg:.1f} 或 波動度 > {std_avg:.2f}",
        "county_good_criteria_label": "優良縣市",
        "county_good_criteria_line1": "平均 AQI < {good_threshold}，或",
        "county_good_criteria_line2": "{good_threshold} ≤ 平均 AQI < {mean_avg:.1f} 且 高污染比例 = 0%",
        # pages/forecast.py (menu order: last)
        "forecast_title": "AQI 預測系統",
        "forecast_select_label": "查看對象",
        "forecast_select_hint": "請選擇縣市",
        "forecast_all": "全台灣總覽",
        "forecast_chart_filter_label": "圖表縣市（可複選）",
        "forecast_summary_title": "數據摘要",
        "forecast_metric_avg": "平均預測值",
        "forecast_metric_peak": "預測最高峰",
        "forecast_metric_best": "最清新時段",
        "forecast_chart_title": "AQI 趨勢預測圖",
        "forecast_axis_time": "預測時間",
        "forecast_axis_aqi": "預測 AQI",
        "forecast_tooltip_county": "縣市",
        "forecast_tooltip_time": "時間",
        "forecast_tooltip_aqi": "預測值",
        "forecast_aqi_prefix": "AQI",
        "forecast_zoom_hint": "可用滑鼠滾輪縮放，拖曳平移圖表。",
        "forecast_error_expired_data": "預測資料已過期，請先更新資料。",
        "forecast_warn_select_county": "請至少選擇一個縣市。",
        "forecast_warn_no_chart_data": "圖表無資料。",
        "forecast_disclaimer": "此數據由 RandomForest 模型計算，僅供參考。",
        "forecast_model_logic": "模型會使用最近時段的 AQI、前 24 小時 AQI、小時、星期與是否週末等特徵，遞迴推估未來 24 小時變化。",
    },
    "en": {
        # pages/trend.py
        "aqi_value_label": "AQI",
        "legend_title": "Series",
        "daily_legend": "Daily AQI",
        "rolling_legend": "7-day Rolling Avg",
        "trend": "Taiwan AQI Trend",
        "aqi_good_label": "Good / Green",
        "aqi_moderate_label": "Moderate / Yellow",
        "aqi_polluted_label": "Polluted / Red",
        "aqi_guide_title": "AQI Interpretation",
        "aqi_good_text": "Normal outdoor activity",
        "aqi_moderate_text": "Air quality is acceptable, but sensitive groups should reduce physical exertion",
        "aqi_polluted_text": "Considered air pollution; reduce outdoor activity",
        "no_trend_data": "No trend data available.",
        "trend_interpretation_title": "How To Read This Trend",
        "trend_interpretation_body": """Daily AQI helps show short-term fluctuations, while the 7-day rolling average highlights the broader trend.<br> 
                        If daily AQI spikes but the rolling average does not rise much, it usually suggests a short-term pollution event.<br> 
                        If both lines rise together, it indicates a more sustained deterioration in air quality.<br> 
                        On the other hand, if the rolling average gradually declines, it suggests that overall air quality is improving over time.""",
        "current_status_title": "Current Status",
        "current_status_placeholder": "Not enough data to interpret the current trend yet.",
        "status_insufficient_data": "Not enough data to interpret the current trend yet.",
        "status_short_term_spike": "The latest daily AQI is clearly higher than the 7-day rolling average, it may indicate a short-term pollution spike or a one-time pollution event.",
        "status_sustained_pollution": "Both OF the latest daily AQI and the 7-day rolling average remain at relatively high levels, it suggests a sustained high-pollution period.",
        "status_improving_trend": "The 7-day rolling average is lower than the previous day, overall air quality may be gradually improving.",
        "status_normal_variation": "The latest daily AQI stays close to the 7-day rolling average and the rolling trend remains stable, the current pattern is more consistent with normal short-term variation.",
        "status_worsening_trend": "The 7-day rolling average continues to rise, it suggests that air quality may be gradually deteriorating.",
        # pages/high_pollution_hours.py
        "hours_y_axis_ratio_label": "High Pollution Probability",
        "hours_y_axis_count_label": "High Pollution Count",
        "hours_tooltip_county": "County",
        "hours_tooltip_ratio": "Probability Ratio",
        "hours_tooltip_count": "High Pollution Count",
        "hours_risk_analysis_desc": "This page shows when high pollution (AQI > 100) is most likely to occur.\nIt compares **probability/risk-based results** with the original **count-based analysis**.",
        "hours_overview_title": "Overview",
        "hours_highest_risk_hour": "Highest-risk hour",
        "hours_highest_risk_ratio": "Highest risk ratio",
        "hours_avg_hourly_risk": "Average hourly risk",
        "hours_overall_risk_title": "Overall High Pollution Risk by Hour",
        "hours_overall_risk_caption": "This chart shows the probability of observing AQI > 100 at each hour of Taiwan.",
        "hours_overall_na": "Overall probability table is not available.",
        "hours_county_risk_title": "County-level Risk Comparison",
        "hours_county_risk_caption": "Select a county to see how the probability of high pollution changes across hours.",
        "hours_county_no_data": "No county-level risk data available for the selected county.",
        "hours_county_na": "County-level probability table is not available.",
        "hours_orig_count_title": "Original Count-based Analysis",
        "hours_orig_count_caption": "This section keeps the original count-based view for comparison. Count shows how many events occurred; risk ratio shows how likely they are.",
        "hours_interpretation_title": "Interpretation",
        "hours_interpretation_desc":  
        "- **Overall High Pollution Risk by Hour**identifies the time windows where high pollution events are most concentrated. Higher ratios in specific hours indicate structured daily patterns rather than random occurrences.\n"
        "- **County-level Risk Comparison**allow comparison between individual counties and the overall trend. If a county's peak hours differ from the overall pattern, it often reflects local emission sources, traffic behavior, or geographic conditions.\n"
        "- **Ratio vs Count Interpretation** compares frequency and actual event volume. A high ratio with low counts may indicate occasional spikes, while both high ratio and high counts suggest consistently high-risk periods.\n"
        "- **Risk Identification** highlights time periods that consistently show elevated ratios across both overall and county-level views, indicating structural high-risk intervals that should be prioritized for monitoring and intervention.",
        # utils.py
        "back_home_button": "Home",
        # shared
        "date_label": "Date",
        "county": "County Air Quality Analysis",
        "all_option": "All",
        "na": "N/A",
        "loading_raw_data": "Loading raw data...",
        "data_not_found": "Data not found.",
        "hours_x_axis_label": "Hour of Day",
        "hours_tooltip_hour": "Hour",
        # shared (county_analysis.py + county_risk.py + utils.py)
        "county_mean_aqi": "Mean AQI",
        "county_std_aqi": "AQI Volatility (Std Dev)",
        "county_high_pol_ratio": "High Pollution Ratio",
        # pages/county_analysis.py
        "county_total_count": "Total Observations",
        "county_page_intro": "This page compares county-level air quality using mean AQI, volatility, and high-pollution ratio.",
        "county_how_to_read_body": "Start with the bubble overview, then switch to single metrics and the full data table for deeper comparison.",
        "county_overall_insight_title": "Interpretation",
        "county_overall_insight_body": "Regions located in the upper-right with larger circles indicate not only higher average pollution but also greater variability and more frequent high pollution events, representing the highest overall risk. In contrast, regions in the lower-left with smaller circles indicate stable and generally clean air conditions.",
        "county_high_risk_label": "Regions currently requiring more attention",
        "county_good_label": "Regions currently showing more stable performance",
        "county_zh": "County (ZH)",
        "county_en": "County (EN)",
        "county_abbrev": "Abbreviation",
        "no_data": "No clear group identified",
        # app.py (home)
        "home_title": "Taiwan Air Quality Dashboard",
        "home_menu": "Home",
        "home_desc": "Choose a page to explore the analysis",
        "hours": "High Pollution Hours",
        "county_overview_title": "County Pollution Profiles & Stability",
        "county_risk_title": "County Risk Analysis",
        "spike_title": "Pollution Spike Detection",
        "forecast_menu": "AQI Forecast System",
        "trend_desc": "View daily average AQI trend",
        "county_overview_desc": "View pollution levels and daily volatility across counties",
        "county_risk_desc": "View high-risk counties and composite risk rankings",
        "hours_desc": "View high pollution hours throughout the day",
        "spike_desc": "View unusual sudden pollution spike events",
        "forecast_desc": "View the next 24-hour AQI forecast trend",
        "home_button_trend": "Open Trend Page",
        "home_button_county": "Open County Page",
        "home_button_hours": "Open High Pollution Page",
        "home_button_spike": "Open Spike Detection",
        "home_button_forecast": "Open AQI Forecast",
        # pages/spike_detection.py
        "spike_pollutant_select": "Select Pollutant",
        "spike_method_select": "Detection Method",
        "spike_method_rolling_threshold": "Rolling Mean Threshold",
        "spike_method_zscore": "Z-Score Anomaly",
        "spike_county_select": "Filter by County",
        "spike_param_settings": "Advanced Parameter Settings",
        "spike_rolling_window": "Rolling Window (Hours)",
        "spike_ratio_threshold": "Ratio Above Baseline",
        "spike_zscore_threshold": "Z-Score Threshold",
        "spike_min_value": "Minimum Value",
        "spike_calculating": "Calculating spike anomalies...",
        "spike_no_data": "No pollution spikes detected. Try adjusting parameters or selecting another county.",
        "hours_spike_title": "Anomaly Heatmap (Macro Overview)",
        "hours_spike_caption": "Analyze outliers across hours and weekdays to spot suspicious time intervals first.",
        "hours_y_axis_weekday_label": "Day of Week",
        "hours_spike_count_legend": "Spike Event Count",
        "hours_tooltip_weekday": "Day of Week",
        "hours_tooltip_spike_count": "Sudden Spike Count",
        "wd_1": "Monday", "wd_2": "Tuesday", "wd_3": "Wednesday", "wd_4": "Thursday", "wd_5": "Friday", "wd_6": "Saturday", "wd_7": "Sunday",
        "spike_total_count": "Total Spike Events",
        "spike_max_title": "Max Observed Value",
        "spike_top_site": "Site w/ Most Spikes",
        "spike_chart_title": "Time-Series Event View (Micro View)",
        "spike_site": "Site",
        "spike_strength": "Spike Strength",
        "spike_event_tab": "Spike Event Detection",
        "spike_summary_tab": "Spike Detection Summary",
        "spike_interpretation_text": "**Interpretation (Event Detection)**\n\n- **Start with the heatmap**: Repeated hotspots by weekday and hour suggest a structural pattern rather than random noise.\n- **Then inspect the time series**: The gray line shows baseline behavior, and red points mark abrupt deviations. Consecutive red points often indicate a continuing event rather than a single outlier.\n- **Recommended workflow**: Use the heatmap to locate suspicious windows first, then verify date, intensity, and duration in the time series to avoid over-interpreting one isolated peak.",
        "spike_detection_summary": "Spike Detection Summary",
        "spike_sample_table_title": "View Spike Sample Table",
        "spike_sample_note": "The table below shows the first 20 spike samples.",
        "county_risk_spike_interpretation_text": "**Interpretation (Summary)**\n\n- **County distribution**: Compares total anomaly counts across counties. Counties that stay high over time are stronger candidates for sustained risk sources.\n- **Hour-of-day distribution**: Identifies when anomalies are most frequent. Consistent peaks at fixed hours are often linked to recurring activity or regular emissions.\n- **Cross-reading rule**: Prioritize county-hour combinations that are high on both charts. For short-lived increases, validate with weather and station status before drawing conclusions.",
        # pages/county_risk.py
        "risk_score": "Risk Score",
        "risk_rank": "Risk Rank",
        "county_risk_intro": "This page evaluates overall air quality risk by integrating long-term pollution, volatility, and frequency of extreme events. A higher score indicates a more hazardous environment.",
        "risk_score_chart_title": "Overall County Risk Score (0-100)",
        "risk_details_title": "View Risk Calculation Details",
        "risk_details_intro": "- First aggregate by county to compute mean AQI, volatility, and high-pollution ratio.\n- Normalize mean AQI and CV with equal 50/50 weight.\n- Apply the high-pollution penalty term and scale the result to 0-100.",
        "risk_time_range_caption": "Data time range used for scoring: {start} ~ {end}",
        "risk_formula_table_title": "Full Calculation Fields",
        "risk_component_mean_norm": "Mean AQI Norm",
        "risk_component_cv_norm": "CV Norm",
        "risk_component_base_score": "Base Score",
        "risk_component_raw_risk": "Penalty-adjusted Raw Risk",
        "risk_formula_note": "Formula: risk_score = normalize((0.5 * mean_aqi_norm + 0.5 * cv_aqi_norm) * (1 + high_pollution_ratio)) * 100",
        "home_button_county_risk": "Go to County Risk Page",
        "analyzing_data": "Analyzing Taiwan's air quality data...",
        "risk_ranking_tab": "Risk Ranking",
        "spike_detection_tab": "Spike Detection",
        "highest_risk": "Highest Risk",
        "total_anomalies": "Total Anomalies",
        "risk_score_table_title": "Risk Score Table",
        "spike_details_title": "View Spike Interpretation Details",
        # pages/county_analysis.py
        "highest_risk_county": "Highest Risk County",
        "best_county": "Best County",
        "highest_volatility": "Highest Volatility",
        "county_overview_chart": "County Overview Map",
        "indicator_ranking": "Indicator Rankings",
        "mean_aqi_ranking": "Mean AQI Ranking",
        "volatility_ranking": "Volatility (Std) Ranking",
        "high_pollution_ratio_ranking": "High Pollution Ratio Ranking",
        "complete_data_table": "Complete Data Table",
        "county_name_comparison": "County Name Comparison",
        "classification_criteria": "Classification Criteria",
        "raw_data_preview": "Raw Data Preview (First 20 Rows)",
        "loading_analysis": "Loading and analyzing Taiwan's air quality data...",
        "stable_air_quality": "Current air quality is stable nationwide",
        "county_risk_table_not_found": "County risk table is not found. Please run main.py data pipeline first.",
        "county_tab_overview": "Overview",
        "county_tab_metrics": "Metrics",
        "county_tab_data": "Full Data",
        "details_info": "Details",
        "county_high_risk_criteria_label": "High-risk counties",
        "county_high_risk_criteria_line1": "Mean AQI > {risk_threshold}, and",
        "county_high_risk_criteria_line2": "also satisfies: Mean AQI > {mean_avg:.1f} or Volatility > {std_avg:.2f}",
        "county_good_criteria_label": "Good-performance counties",
        "county_good_criteria_line1": "Mean AQI < {good_threshold}, or",
        "county_good_criteria_line2": "{good_threshold} ≤ Mean AQI < {mean_avg:.1f} and High Pollution Ratio = 0%",
        # pages/forecast.py (menu order: last)
        "forecast_title": "AQI Forecast System",
        "forecast_select_label": "View Selection",
        "forecast_select_hint": "Please select a county",
        "forecast_all": "National Overview",
        "forecast_chart_filter_label": "Chart Counties (multi-select)",
        "forecast_summary_title": "Summary",
        "forecast_metric_avg": "Avg Forecast",
        "forecast_metric_peak": "Peak Forecast",
        "forecast_metric_best": "Best Air Quality",
        "forecast_chart_title": "AQI Trend Forecast",
        "forecast_axis_time": "Forecast Time",
        "forecast_axis_aqi": "Predicted AQI",
        "forecast_tooltip_county": "County",
        "forecast_tooltip_time": "Time",
        "forecast_tooltip_aqi": "Predicted AQI",
        "forecast_aqi_prefix": "AQI",
        "forecast_zoom_hint": "Use mouse wheel to zoom and drag to pan.",
        "forecast_error_expired_data": "Forecast data has expired. Please refresh data first.",
        "forecast_warn_select_county": "Please select at least one county for the chart.",
        "forecast_warn_no_chart_data": "No data available for selected chart counties.",
        "forecast_disclaimer": "This forecast is generated by a RandomForest model and is for reference only.",
        "forecast_model_logic": "The model recursively forecasts the next 24 hours using recent AQI, 24-hour lag AQI, hour-of-day, day-of-week, and weekend features.",
    }
}