TEXT = {
    "zh": {
        "site_title": "台灣空氣品質儀表板",
        "site_subtitle": "Taiwan Air Quality Dashboard",
        "language": "語言 / Language",
        "language_toggle_label": "語言切換",
        "menu_title": "導覽",
        "home_menu": "首頁",
        "home_title": "台灣空氣品質儀表板",
        "home_desc": "請選擇想查看的分析頁面",
        "go_to_page": "前往頁面",
        "overview": "總覽",
        "trend": "台灣 AQI 趨勢",
        "county": "各縣市空氣品質分析",
        "hours": "高污染時段",
        "overview_desc": "查看整體 AQI 指標與快速摘要",
        "trend_desc": "查看每日平均 AQI 變化趨勢",
        "county_desc": "查看各縣市平均 AQI 分布",
        "hours_desc": "查看一天中高污染時段分布",
        "avg_aqi": "平均 AQI",
        "max_aqi": "最高 AQI",
        "high_pollution_count": "高污染時段數",
        "line_chart_title": "台灣 AQI 趨勢",
        "date_label": "日期",
        "month_label": "月份",
        "aqi_value_label": "AQI 數值",
        "rolling_7d_avg": "7 日滾動平均 AQI",
        "legend_title": "線條",
        "daily_legend": "Daily AQI",
        "rolling_legend": "7-day Rolling Avg",
        "chart_zoom_hint": "可用滑鼠滾輪縮放、拖曳平移；雙擊圖表可回到原始視角。",
        "county_chart_title": "各縣市汙染狀況分析",
        "hours_chart_title": "高污染時段",
        "back_home_button": "回到首頁",
        "aqi_guide_title": "AQI 分級說明",
        "aqi_good_label": "良好 / Green",
        "aqi_good_text": "可正常進行戶外活動",
        "county_stability_title": "各縣市空氣品質分析",
        "county_mean_aqi": "平均 AQI",  
        "county_std_aqi": "AQI 波動度（標準差）",
        "county_high_pol_ratio": "高污染比例",
        "county_total_count": "觀測總數",
        "county_mean_rank": "平均 AQI 排名",
        "county_std_rank": "波動度排名",
        "county_ratio_rank": "高污染比例排名",
        "county_page_intro": "這頁從三個角度比較各縣市空氣品質：平均 AQI 代表整體污染程度，AQI 波動度代表日常變化是否劇烈，高污染比例代表 AQI 超過 100 的發生頻率。",
        "hours_risk_analysis_title": "高污染風險分析",
        "hours_risk_analysis_desc": "此頁面不僅使用原始次數，更透過機率/風險比例來呈現各時段發生高污染 (AQI > 100) 的可能性。",
        "hours_prob_by_hour": "各時段高污染發生機率",
        "hours_view_overall_ratio": "檢視整體比例資料",
        "hours_overall_ratio_na": "目前無整體比例資料。",
        "hours_original_count_analysis": "原始發生次數分析",
        "hours_view_raw_count": "檢視原始次數資料",
        "county_top_mean_title": "平均 AQI 最高",
        "county_top_mean_desc": "代表長期整體污染程度較高",
        "county_top_std_title": "波動度最高",
        "county_top_std_desc": "代表 AQI 日常變化較劇烈",
        "county_top_ratio_title": "高污染比例最高",
        "county_top_ratio_desc": "代表 AQI 超過 100 的情況較常出現",
        "county_chart_mean_title": "平均 AQI",
        "county_chart_mean_desc": "數值越高，代表長期平均空氣品質越差。",
        "county_chart_std_title": "AQI 波動度（標準差）",
        "county_chart_std_desc": "數值越高，代表日與日之間變化越明顯。",
        "county_chart_ratio_title": "高污染比例",
        "county_chart_ratio_desc": "比例越高，代表 AQI 超過 100 的情況越常發生。",
        "county_table_title": "縣市指標明細",
        "county_table_desc": "下表用來查看完整數值與排序，可搭配上方圖表交叉比較。",
        "county_how_to_read_body": "若某縣市平均 AQI 高，代表整體污染水準偏高；若波動度也高，表示不只平均較差，日常空氣品質也較不穩定；若高污染比例同時偏高，則代表 AQI 超過 100 的情況更常出現。三個指標一起看，比單看平均值更能判斷空氣品質風險。",
        "county_name_reference_title": "縣市中英文對照與縮寫",
        "county_zh": "中文縣市名",
        "county_en": "English County Name",
        "county_abbrev": "英文縮寫",
        "county_overall_insight_title": "綜合解讀",
        "county_overall_insight_body": "右上角且圓較大的縣市，表示不僅平均污染程度較高，變動也較劇烈，且高污染事件發生頻率高，屬於整體風險最高的區域。 相對地，左下角且圓較小的縣市，代表空氣品質穩定且較少出現高污染情況。",
        "county_high_risk_label": "較需注意的縣市",
        "county_good_label": "表現較穩定的縣市",
        "no_data": "無明顯分類結果",
        "aqi_moderate_label": "普通 / Yellow",
        "aqi_moderate_text": "空氣品質可接受，但敏感族群（如呼吸道疾病患者）應減少體力消耗",
        "aqi_polluted_label": "污染 / Red",
        "aqi_polluted_text": "已屬空氣污染，請減少戶外活動",
        "trend_interpretation_title": "趨勢解讀",
        "trend_interpretation_body": """Daily AQI 用來顯示短期波動，而 7-day rolling average 則用來呈現較整體的趨勢。<br>
                                    如果 Daily AQI 明顯升高，但 7-day rolling average 沒有明顯上升，通常代表這比較像短期污染事件。<br>
                                    如果兩條線一起上升，則表示空氣品質變差可能不是單日現象，而是較持續的惡化趨勢。<br>
                                    相反地，如果 7-day rolling average 逐漸下降，則代表整體空氣品質可能正在慢慢改善。""",
        "current_status_title": "目前狀態判讀",
        "current_status_placeholder": "目前資料不足，暫時無法判讀整體趨勢。",
        "status_insufficient_data": "目前資料不足，暫時無法判讀整體趨勢。",
        "status_short_term_spike": "最新 Daily AQI 明顯高於 7-day rolling average，代表最近可能出現短期污染升高或單次污染事件。",
        "status_sustained_pollution": "最新 Daily AQI 與 7-day rolling average 都維持在偏高水準，代表目前可能處於持續性的高污染狀態。",
        "status_improving_trend": "7-day rolling average 比前一天下降，代表整體空氣品質可能正在逐步改善。",
        "status_normal_variation": "最新 Daily AQI 與 7-day rolling average 差距不大，且移動平均變化平穩，代表目前整體以正常波動為主。",
        "status_worsening_trend": "7-day rolling average 持續上升，代表近期空氣品質可能有逐步變差的趨勢。",
        "monthly_pattern_title": "月度 AQI 型態（可選）",
        "monthly_avg_aqi": "月平均 AQI",
        "trend_future_space": "此區塊保留給後續擴充：季節性分解、異常點偵測、節假日影響等。",
        "advanced_analysis": "後續可擴充分析",
        "advanced_analysis_info": """
這個區塊未來可以加入：

- 污染 spike 偵測
- 測站分析
- 污染物分布（PM2.5 / O3）
- 時間序列模型
""",
        "daily_avg_aqi": "每日平均 AQI",
        "county_avg_aqi": "各縣市平均 AQI",
        "high_pollution_hours_label": "高污染次數",
        "home_button_overview": "進入總覽頁",
        "home_button_trend": "進入趨勢頁",
        "home_button_county": "進入縣市分析頁",
        "home_button_hours": "進入高污染時段頁",
    },
    "en": {
        "site_title": "Taiwan Air Quality Dashboard",
        "site_subtitle": "Taiwan Air Quality Dashboard",
        "language": "Language / 語言",
        "language_toggle_label": "Language",
        "menu_title": "Navigation",
        "home_menu": "Home",
        "home_title": "Taiwan Air Quality Dashboard",
        "home_desc": "Choose a page to explore the analysis",
        "go_to_page": "Go to page",
        "overview": "Overview",
        "trend": "Taiwan AQI Trend",
        "county": "County Air Quality Analysis",
        "hours": "High Pollution Hours",
        "overview_desc": "View overall AQI metrics and quick summary",
        "trend_desc": "View daily average AQI trend",
        "county_desc": "View average AQI across counties",
        "hours_desc": "View high pollution hours throughout the day",
        "avg_aqi": "Average AQI",
        "max_aqi": "Max AQI",
        "high_pollution_count": "High Pollution Count",
        "line_chart_title": "Taiwan AQI Trend",
        "date_label": "Date",
        "month_label": "Month",
        "aqi_value_label": "AQI",
        "rolling_7d_avg": "7-day Rolling Avg AQI",
        "legend_title": "Series",
        "daily_legend": "Daily AQI",
        "rolling_legend": "7-day Rolling Avg",
        "chart_zoom_hint": "Use mouse wheel to zoom and drag to pan; double-click the chart to reset the original view.",
        "county_chart_title": "Pollution by County",
        "hours_chart_title": "High Pollution Hours",
        "back_home_button": "Back to Home",
        "aqi_guide_title": "AQI Interpretation",
        "aqi_good_label": "Good / Green",
        "aqi_good_text": "Normal outdoor activity",
        "county_stability_title": "County Air Quality Analysis",
        "county_mean_aqi": "Mean AQI",
        "county_std_aqi": "AQI Volatility (Std Dev)",
        "county_high_pol_ratio": "High Pollution Ratio",
        "county_total_count": "Total Observations",
        "county_mean_rank": "Mean Rank",
        "county_std_rank": "Volatility Rank",
        "county_ratio_rank": "Ratio Rank",
        "county_interpretation_text": "High average AQI indicates consistently polluted areas, whereas high volatility (Std Dev) highlights counties prone to sudden, extreme pollution events. The High Pollution Ratio shows how often a county exceeds AQI 100.",
        "county_page_intro": "This page compares county-level air quality from three perspectives: mean AQI reflects the overall pollution level, AQI volatility reflects how unstable day-to-day conditions are, and the high-pollution ratio shows how often AQI exceeds 100.",
        "hours_risk_analysis_title": "High Pollution Risk Analysis",
        "hours_risk_analysis_desc": "This page shows which hours are more likely to experience high pollution (AQI > 100), using probability/risk ratios instead of only raw counts.",
        "hours_prob_by_hour": "Overall High Pollution Probability by Hour",
        "hours_view_overall_ratio": "View Overall Ratio Data",
        "hours_overall_ratio_na": "Overall ratio data not available.",
        "hours_original_count_analysis": "Original Count-Based Analysis",
        "hours_view_raw_count": "View Raw Count Data",
        "county_top_mean_title": "Highest Mean AQI",
        "county_top_mean_desc": "Indicates a higher long-term overall pollution level",
        "county_top_std_title": "Highest Volatility",
        "county_top_std_desc": "Indicates stronger day-to-day AQI fluctuations",
        "county_top_ratio_title": "Highest High-Pollution Ratio",
        "county_top_ratio_desc": "Indicates AQI exceeds 100 more frequently",
        "county_chart_mean_title": "Mean AQI",
        "county_chart_mean_desc": "Higher values indicate worse long-term average air quality.",
        "county_chart_std_title": "AQI Volatility (Std Dev)",
        "county_chart_std_desc": "Higher values indicate stronger day-to-day variation.",
        "county_chart_ratio_title": "High-Pollution Ratio",
        "county_chart_ratio_desc": "Higher values indicate AQI exceeds 100 more often.",
        "county_table_title": "County Metrics Table",
        "county_table_desc": "Use the table below to inspect detailed values and rankings alongside the charts above.",
        "county_how_to_read_body": "If a county has a high mean AQI, its overall pollution level is relatively high. If its volatility is also high, daily air quality is not only worse on average but also less stable. If the high-pollution ratio is high as well, AQI above 100 occurs more frequently. Looking at these three metrics together provides a better picture of air-quality risk than using the mean alone.",
        "county_name_reference_title": "County Name Reference and Abbreviation",
        "county_zh": "Chinese County Name",
        "county_en": "English County Name",
        "county_abbrev": "Abbreviation",
        "county_overall_insight_title": "Interpretation",
        "county_overall_insight_body": "Regions located in the upper-right with larger circles indicate not only higher average pollution but also greater variability and more frequent high pollution events, representing the highest overall risk. In contrast, regions in the lower-left with smaller circles indicate stable and generally clean air conditions.",
        "county_high_risk_label": "Regions currently requiring more attention",
        "county_good_label": "Regions currently showing more stable performance",
        "no_data": "No clear group identified",
        "aqi_moderate_label": "Moderate / Yellow",
        "aqi_moderate_text": "Air quality is acceptable, but sensitive groups should reduce physical exertion",
        "aqi_polluted_label": "Polluted / Red",
        "aqi_polluted_text": "Considered air pollution; reduce outdoor activity",
        "trend_interpretation_title": "How To Read This Trend",
        "trend_interpretation_body": """Daily AQI helps show short-term fluctuations, while the 7-day rolling average highlights the broader trend.<br> 
                                    If daily AQI spikes but the rolling average does not rise much, it usually suggests a short-term pollution event.<br> 
                                    If both lines rise together, it indicates a more sustained deterioration in air quality.<br> 
                                    On the other hand, if the rolling average gradually declines, it suggests that overall air quality is improving over time.""",
        "current_status_title": "Current Status",
        "current_status_placeholder": "Not enough data to interpret the current trend yet.",
        "status_insufficient_data": "Not enough data to interpret the current trend yet.",
        "status_short_term_spike": "The latest daily AQI is clearly higher than the 7-day rolling average, it may indicate a short-term pollution spike or a one-time pollution event.",
        "status_sustained_pollution": "Both OF the latest daily AQI and the 7-day rolling average remain at relatively high levels, it suggests a sustained high-pollution period.",
        "status_improving_trend": "The 7-day rolling average is lower than the previous day, overall air quality may be gradually improving.",
        "status_normal_variation": "The latest daily AQI stays close to the 7-day rolling average and the rolling trend remains stable, the current pattern is more consistent with normal short-term variation.",
        "status_worsening_trend": "The 7-day rolling average continues to rise, it suggests that air quality may be gradually deteriorating.",
        "monthly_pattern_title": "Monthly AQI Pattern (Optional)",
        "monthly_avg_aqi": "Monthly Average AQI",
        "trend_future_space": "This space is intentionally reserved for future extensions such as seasonality, anomaly detection, and holiday effects.",
        "advanced_analysis": "Future Advanced Analysis",
        "advanced_analysis_info": """
This section can be extended with:

- Pollution spike detection
- Station-level analysis
- Pollutant distribution (PM2.5 / O3)
- Time series models
""",
        "daily_avg_aqi": "Daily Average AQI",
        "county_avg_aqi": "Average AQI by County",
        "high_pollution_hours_label": "High Pollution Count",
        "home_button_overview": "Open Overview",
        "home_button_trend": "Open Trend Page",
        "home_button_county": "Open County Page",
        "home_button_hours": "Open High Pollution Page",
    }
}